// Code generated by protoc-gen-go. DO NOT EDIT.
// source: versionserver.proto

/*
Package versionserver is a generated protocol buffer package.

It is generated from these files:
	versionserver.proto

It has these top-level messages:
	Version
	GetVersionRequest
	GetVersionResponse
	SetVersionRequest
	SetVersionResponse
*/
package versionserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Version struct {
	Key    string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value  int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Setter string `protobuf:"bytes,3,opt,name=setter" json:"setter,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Version) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Version) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Version) GetSetter() string {
	if m != nil {
		return m.Setter
	}
	return ""
}

type GetVersionRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetVersionRequest) Reset()                    { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()               {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetVersionRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetVersionResponse struct {
	Version *Version `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *GetVersionResponse) Reset()                    { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()               {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetVersionResponse) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type SetVersionRequest struct {
	Set *Version `protobuf:"bytes,1,opt,name=set" json:"set,omitempty"`
}

func (m *SetVersionRequest) Reset()                    { *m = SetVersionRequest{} }
func (m *SetVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*SetVersionRequest) ProtoMessage()               {}
func (*SetVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SetVersionRequest) GetSet() *Version {
	if m != nil {
		return m.Set
	}
	return nil
}

type SetVersionResponse struct {
	Response *Version `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *SetVersionResponse) Reset()                    { *m = SetVersionResponse{} }
func (m *SetVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*SetVersionResponse) ProtoMessage()               {}
func (*SetVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetVersionResponse) GetResponse() *Version {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*Version)(nil), "versionserver.Version")
	proto.RegisterType((*GetVersionRequest)(nil), "versionserver.GetVersionRequest")
	proto.RegisterType((*GetVersionResponse)(nil), "versionserver.GetVersionResponse")
	proto.RegisterType((*SetVersionRequest)(nil), "versionserver.SetVersionRequest")
	proto.RegisterType((*SetVersionResponse)(nil), "versionserver.SetVersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VersionServer service

type VersionServerClient interface {
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	SetVersion(ctx context.Context, in *SetVersionRequest, opts ...grpc.CallOption) (*SetVersionResponse, error)
}

type versionServerClient struct {
	cc *grpc.ClientConn
}

func NewVersionServerClient(cc *grpc.ClientConn) VersionServerClient {
	return &versionServerClient{cc}
}

func (c *versionServerClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := grpc.Invoke(ctx, "/versionserver.VersionServer/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionServerClient) SetVersion(ctx context.Context, in *SetVersionRequest, opts ...grpc.CallOption) (*SetVersionResponse, error) {
	out := new(SetVersionResponse)
	err := grpc.Invoke(ctx, "/versionserver.VersionServer/SetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VersionServer service

type VersionServerServer interface {
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	SetVersion(context.Context, *SetVersionRequest) (*SetVersionResponse, error)
}

func RegisterVersionServerServer(s *grpc.Server, srv VersionServerServer) {
	s.RegisterService(&_VersionServer_serviceDesc, srv)
}

func _VersionServer_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/versionserver.VersionServer/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServerServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionServer_SetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServerServer).SetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/versionserver.VersionServer/SetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServerServer).SetVersion(ctx, req.(*SetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VersionServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "versionserver.VersionServer",
	HandlerType: (*VersionServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _VersionServer_GetVersion_Handler,
		},
		{
			MethodName: "SetVersion",
			Handler:    _VersionServer_SetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "versionserver.proto",
}

func init() { proto.RegisterFile("versionserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4b, 0x85, 0x40,
	0x14, 0x86, 0x9b, 0x86, 0xb4, 0x4e, 0x08, 0x79, 0x0a, 0x91, 0x56, 0x36, 0x10, 0xb8, 0x92, 0xb0,
	0x75, 0xdb, 0x3e, 0xb6, 0x0e, 0xb4, 0x2f, 0x38, 0x8b, 0x28, 0xd2, 0x66, 0x46, 0xa1, 0x9f, 0xd6,
	0xbf, 0x8b, 0x19, 0xc7, 0xba, 0xde, 0xb9, 0x5e, 0x77, 0xe7, 0x1c, 0x1e, 0x9f, 0xf7, 0x55, 0x84,
	0xf3, 0x81, 0x94, 0x7e, 0x6b, 0x3f, 0x35, 0xa9, 0x81, 0x54, 0xd5, 0xa9, 0xd6, 0xb4, 0x98, 0xcc,
	0x8e, 0xe2, 0x09, 0xe2, 0xe7, 0xf1, 0x80, 0x67, 0xc0, 0xdf, 0xe9, 0x3b, 0x67, 0x05, 0x2b, 0x4f,
	0x1a, 0x3b, 0xe2, 0x05, 0x1c, 0x0d, 0x2f, 0x1f, 0x3d, 0xe5, 0x87, 0x05, 0x2b, 0x79, 0x33, 0x2e,
	0x98, 0x41, 0xa4, 0xc9, 0x18, 0x52, 0x39, 0x77, 0xa8, 0xdf, 0xc4, 0x35, 0xa4, 0x0f, 0x64, 0xbc,
	0xad, 0xa1, 0xaf, 0x9e, 0xb4, 0x09, 0xa5, 0xe2, 0x1e, 0x70, 0x13, 0xd3, 0x9d, 0xed, 0x82, 0x37,
	0x10, 0xfb, 0x62, 0x2e, 0xec, 0xb4, 0xce, 0xaa, 0x79, 0xfb, 0xe9, 0x81, 0x09, 0x13, 0x77, 0x90,
	0xca, 0x20, 0xae, 0x04, 0xae, 0xc9, 0xb8, 0xb8, 0x65, 0x85, 0x45, 0xc4, 0x23, 0xa0, 0x0c, 0x6b,
	0xd4, 0x70, 0xac, 0xfc, 0xbc, 0x22, 0xf9, 0xe3, 0xea, 0x1f, 0x06, 0x89, 0xbf, 0x4a, 0xc7, 0xa0,
	0x04, 0xf8, 0x7f, 0x45, 0x2c, 0xb6, 0x0c, 0xc1, 0x47, 0xba, 0xbc, 0xda, 0x43, 0x8c, 0x21, 0xe2,
	0xc0, 0x4a, 0xe5, 0xb2, 0x54, 0xae, 0x4a, 0xe5, 0x0e, 0xe9, 0x6b, 0xe4, 0x7e, 0x8a, 0xdb, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xca, 0x19, 0x91, 0x2b, 0x02, 0x00, 0x00,
}
